<html>
    <head>
      <link rel="stylesheet" type="text/css" href="style.css"/>
      <script src="stories.js"></script>
    </head>
    <body>
        <div id="topbar">
            <img id="logo" src="images/tcg-logo-CON.png" alt="Transformers - Trading Card Game"/>
            <ul id="menu">
                <li class="selected"><a href="test.html">Home</a></li>
                <li><a href="cards.html">Cards</a></li>
                <li><a href="how-where.html">How &amp; Where to Play</a></li>
                <li><a href="rules.html">Rules</a></li>
                <li class="standout"><a href="links.html">Links</a></li>
            </ul>
        </div>
